#!/usr/bin/env bash

set -uo pipefail;

####################################
# Ensure we can execute standalone #
####################################

function early_death() {
  echo "[FATAL] ${0}: ${1}" >&2;
  exit 1;
};

if [ -z "${PKRENV_ROOT:-""}" ]; then
  # http://stackoverflow.com/questions/1055671/how-can-i-get-the-behavior-of-gnus-readlink-f-on-a-mac
  readlink_f() {
    local target_file="${1}";
    local file_name;

    while [ "${target_file}" != "" ]; do
      cd "$(dirname ${target_file})" || early_death "Failed to 'cd \$(dirname ${target_file})' while trying to determine PKRENV_ROOT";
      file_name="$(basename "${target_file}")" || early_death "Failed to 'basename \"${target_file}\"' while trying to determine PKRENV_ROOT";
      target_file="$(readlink "${file_name}")";
    done;

    echo "$(pwd -P)/${file_name}";
  };

  PKRENV_ROOT="$(cd "$(dirname "$(readlink_f "${0}")")/.." && pwd)";
  [ -n "${PKRENV_ROOT}" ] || early_death "Failed to 'cd \"\$(dirname \"\$(readlink_f \"${0}\")\")/..\" && pwd' while trying to determine PKRENV_ROOT";
else
  PKRENV_ROOT="${PKRENV_ROOT%/}";
fi;
export PKRENV_ROOT;

if [ -n "${PKRENV_HELPERS:-""}" ]; then
  log 'debug' 'PKRENV_HELPERS is set, not sourcing helpers again';
else
  [ "${PKRENV_DEBUG:-0}" -gt 0 ] && echo "[DEBUG] Sourcing helpers from ${PKRENV_ROOT}/lib/pkrenv-helpers.sh";
  if source "${PKRENV_ROOT}/lib/pkrenv-helpers.sh"; then
    log 'debug' 'Helpers sourced successfully';
  else
    early_death "Failed to source helpers from ${PKRENV_ROOT}/lib/pkrenv-helpers.sh";
  fi;
fi;

# Ensure libexec and bin are in $PATH
for dir in libexec bin; do
  case ":${PATH}:" in
    *:${PKRENV_ROOT}/${dir}:*) log 'debug' "\$PATH already contains '${PKRENV_ROOT}/${dir}', not adding it again";;
    *)
      log 'debug' "\$PATH does not contain '${PKRENV_ROOT}/${dir}', prepending and exporting it now";
      export PATH="${PKRENV_ROOT}/${dir}:${PATH}";
      ;;
  esac;
done;

#####################
# Begin Script Body #
#####################

[ "${#}" -ne 0 ] \
  && log 'error' "usage: pkrenv pin";

[ -d "${PKRENV_CONFIG_DIR}/versions/" ] \
  || log 'error' 'No versions available. Please install one with: pkrenv install';

[[ -x "${PKRENV_CONFIG_DIR}/versions" && -r "${PKRENV_CONFIG_DIR}/versions" ]] \
  || log 'error' "pkrenv versions directory is inaccessible: ${PKRENV_CONFIG_DIR}/versions";

version_name="$(pkrenv-version-name 2>/dev/null || true)" \
  && log 'debug' "pkrenv-version-name reported: ${version_name}";

echo "${version_name}" > .packer-version;
log 'info' "Pinned version by writing \"${version_name}\" to $(pwd)/.packer-version";

exit 0;
